kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  namespace: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  namespace: sonarqube
  labels:
    app: postgres
data:
  #POSTGRESQL_USERNAME: ${{ secrets.POSTGRESQL_USERNAME }}
  #POSTGRESQL_DATABASE: ${{ secrets.POSTGRESQL_DATABASE }}
  #POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}
  POSTGRESQL_USERNAME: sonar_user
  POSTGRESQL_DATABASE: sonar_db
  POSTGRESQL_PASSWORD: S0N4RQUB3
---
