apiVersion: v1
kind: Service
metadata:
  name: service-gkeapp
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: gkeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-gkeapp
  labels:
    app: gkeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gkeapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: gkeapp
    spec:
      containers:
        - name: gkeapp
          image: europe-west2-docker.pkg.dev/lofty-object-378217/web-app/stateless:latest
          env:
            - name: NODE_ENV
              value: 'production'
            - name: PORT
              value: '3000'
            #- name: PGHOST
            #  value: '${db_host}'
            #- name: PGPORT
            #  value: '${db_port}'
            #- name: PGDATABASE
            #  value: '${db_name}'
            #- name: PGUSER
            #  value: '${db_username}'
            #- name: PGPASSWORD
            #  value: '${db_password}'
          ports:
            - containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
            requests:
              cpu: 250m
              memory: 500Mi
---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: ingress-gkeapp
#spec:
#  backend:
#    serviceName: service-gkeapp
#    servicePort: 80