apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: wp-champ
spec:
  domains:
    - projectchamp.info
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wp-ingress
  annotations:
    networking.gke.io/managed-certificates: "wp-champ"
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/v1beta1.FrontendConfig: "sslpolicy"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    #kubernetes.io/ingress.global-static-ip-name: "lb-ip"
spec:
  rules:
  - host: projectchamp.info
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /
        backend:
          service:
            name: wordpress
            port:
              number: 80