apiVersion: v1
kind: Service
metadata:
  namespace: wordpress
  labels:
    app: wordpress
  name: wordpress
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress
# [END gke_wordpress_persistent_disks_wordpress_service_service_wordpress]