apiVersion: v1
kind: Namespace
metadata:
  name: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: europe-west2-docker.pkg.dev/lofty-object-378217/web/webapp:latest #quay.io/fairwinds/k8s-workshop:latest
          command: ["ruby", "app/app.rb"]
          ports:
          - containerPort: 8080
            name: http
          env:
            - name: REDIS_HOST
              value: 'redis-primary'
            - name: REDIS_PORT
              value: '6379'
            #- name: SECRET1
            #  value:
            #- name: DEPENDENCY_URL
            #  value:
            - name: DEPENDENCY_REQUIRE_TLS
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: webapp
  labels:
    app: webapp
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: webapp
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp
  labels:
    app: webapp
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8080
  type: NodePort
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: webapp-cert
  namespace: webapp
spec:
  domains:
    - webapp.d-e-l-o.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  namespace: webapp
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "web-address"
    networking.gke.io/managed-certificates: "webapp-cert"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: webapp.d-e-l-o.com
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: webapp-service
            port: 
              number: 8080