name: WP deploy

on:
  push:
    branches: [ "main" ]

env:
  #PROJECT_ID: champ-392921
  MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME}}
  pwd: ${{ secrets.PWD}}
  MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE}}
  wpsa: ${{ secrets.WPSA }}
jobs:
  setup-build-publish-deploy:
    name: WP deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/352111373069/locations/global/workloadIdentityPools/github-wif-pool/providers/githubwif'
        service_account: 'github-sa@champ-392921.iam.gserviceaccount.com'

    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ secrets.GKE}}
        location: europe-west2
    
    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
    # Deploy the Docker image to the GKE cluster
    - name: create secret from json and envsbust
      run: |-
        cat wordpress/wordpress_cloudsql.yaml.template | envsubst > wordpress/wordpress_cloudsql.yaml

    - name: Deploy manifests to gke
      run: |-
        kubectl delete -f wordpress/mysql-volumeclaim.yaml
        kubectl delete -f wordpress/mysql.yaml
        kubectl delete -f wordpress/mysql-service.yaml        
        kubectl delete -f wordpress/wordpress-volumeclaim.yaml        
        kubectl delete -f wordpress/wordpress.yaml
        kubectl delete -f wordpress/manifests.yaml  
        kubectl delete -f wordpress/wordpress_cloudsql.yaml
        kubectl delete -f wordpress/wordpress-service.yaml
        kubectl delete -f wordpress/ingress.yaml       